# Alembic migration scripts directory
"""initial migration

Revision ID: 862f74b7af38
Revises: 
Create Date: 2026-01-23 17:31:25.385817

"""
from alembic import op
import sqlalchemy as sa


revision = '862f74b7af38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_loan_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('loan_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=False),
    sa.Column('interest_rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loan_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_loan_id'), 'payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###
